### ISSUE TITLE
os_release falsly relies on yumvar['releasever'] being a number

### ISSUE THREAD

**Issue by 5nafu** [yadt/yadt-minion#17]
On Oracle Linux yum reports a releasever for example as  "6Server". Casting this to a float fails:
```
WARNING  HOSTNAME /usr/bin/yadt-status stderr: Traceback (most recent call last):
WARNING  HOSTNAME /usr/bin/yadt-status stderr:   File "/usr/bin/yadt-status.py", line 7, in <module>
WARNING  HOSTNAME /usr/bin/yadt-status stderr:     ys = Status()
WARNING  HOSTNAME /usr/bin/yadt-status stderr:   File "/usr/lib/python2.6/site-packages/yadtminion/__init__.py", line 268, in __init__
WARNING  HOSTNAME /usr/bin/yadt-status stderr:     self.setup_services()
WARNING  HOSTNAME /usr/bin/yadt-status stderr:   File "/usr/lib/python2.6/site-packages/yadtminion/__init__.py", line 365, in setup_services
WARNING  HOSTNAME /usr/bin/yadt-status stderr:     service_artefacts = self.get_service_init_details(service)
WARNING  HOSTNAME /usr/bin/yadt-status stderr:   File "/usr/lib/python2.6/site-packages/yadtminion/__init__.py", line 346, in get_service_init_details
WARNING  HOSTNAME /usr/bin/yadt-status stderr:     init_scripts, init_type = self.get_init_scripts_and_type(service['name'])
WARNING  HOSTNAME /usr/bin/yadt-status stderr:   File "/usr/lib/python2.6/site-packages/yadtminion/__init__.py", line 315, in get_init_scripts_and_type
WARNING  HOSTNAME /usr/bin/yadt-status stderr:     os_release = float(yb.conf.yumvar['releasever'])
WARNING  HOSTNAME /usr/bin/yadt-status stderr: ValueError: invalid literal for float(): 6Server
ERROR    /usr/bin/yadt-status@HOSTNAME: A process has ended with a probable error condition: process ended with exit code 1.
```

**Comment by mriehl** [comment]
I think I'd just mangle out `server` from the lowercased releasever.
Something like `.lower().replace('server', '')` before turning it into a `float`.

**Comment by range** [comment]
Why not use 'lsb_release -r" for finding out the release version?

```
rangenendt@tuvora11 ~ $ lsb_release -r
Release:	6.7
rangenendt@tuvora11 ~ $ Abgemeldet
Connection to tuvora11 closed.
rangenendt@berman01 ~ $ lsb_release -r
Release:	6.7
rangenendt@berman01 ~ $
```

**Comment by mriehl** [comment]
It also requires parsing (arguably more than the yum releasever) so I'd rather use the yum view instead of shelling out. This code path is called a lot.
